modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="vanilishend"
version="1.0.0"
displayName="VanilishEnd"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="PromasterYTJava (Totally Not Youtuber)"
description='''
This Mod Revamps The Minecraft End But, In A Vanilla Style Way
'''

[[dependencies.vanilishend]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




